name: Build and Commit Wireviz Output

on:
  pull_request:
    paths:
      - 'lampe-wireviz.yml'
  workflow_dispatch:

jobs:
  build-wireviz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Wireviz
        run: pip install wireviz

      - name: Install Graphviz
        run: sudo apt-get update && sudo apt-get install -y graphviz

      - name: Generate output files with Wireviz
        run: wireviz lampe-wireviz.yml

      - name: Commit and push generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-generate Wireviz output files"
          if [ -n "$GITHUB_HEAD_REF" ]; then
            git push origin HEAD:$GITHUB_HEAD_REF
          else
            BRANCH_NAME=$(echo "${GITHUB_REF#refs/heads/}")
            if [ -n "$BRANCH_NAME" ] && [ "$BRANCH_NAME" != "$GITHUB_REF" ]; then
              git push origin HEAD:$BRANCH_NAME
            else
              echo "Could not determine branch to push to."
            fi
          fi

      - name: Run unit tests
        run: |
          pip install pytest
          pytest tests/unit

      - name: Run E2E tests (placeholder)
        run: echo "Replace this with your E2E test command (e.g., npx cypress run, npx playwright test, etc.)"
