name: Build and Commit Wireviz Output

on:
  pull_request:
    paths:
      - 'lampe-wireviz.yml'
  workflow_dispatch:

jobs:
  build-wireviz:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout PR branch
        uses: actions/checkout@v4
        with:
          persist-credentials: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Wireviz
        run: pip install wireviz

      - name: Generate output files with Wireviz
        run: wireviz lampe-wireviz.yml

      - name: Commit and push generated files
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add .
          git diff --cached --quiet || git commit -m "Auto-generate Wireviz output files"
          git push

      - name: Run unit tests
        run: |
          pip install pytest
          pytest tests/unit

      - name: Run E2E tests (placeholder)
        run: echo "Replace this with your E2E test command (e.g., npx cypress run, npx playwright test, etc.)"
